### ISSUE TITLE
Release or upload to maven repo?

### ISSUE THREAD

**Issue by rusefi** [j123b567/java-intelhex-parser#6]
Time flies forward and Ant is no longer the most popular build framework. An official release on github would be nice :)

Feel free to take the the jar compiled with java 8 at https://github.com/rusefi/java-intelhex-parser/releases/tag/20200627

**Comment by j123b567** [comment]
I'm not Java developer and this repository is just a side effect of my other project.

I don't have any experioence with other build tools. Few years ago, I tried maven, but it tried to download several gigabytes of data just for simple dependency so I reject it.

Maybee, it is now more usable so the prefered way should be https://github.com/j123b567/java-intelhex-parser/packages ?
If you can provide maven build files, I can publish it as package.

**Comment by rusefi** [comment]
Yes https://github.com/j123b567/java-intelhex-parser/packages would work just fine.

My compiled jar is available above if you do not want to compile.

Maven is not the cool kit any more, gradle is the coolest kid in java build universe these days - for instance that's the Android development build tool.

You only download several gigabyte if you depend on several gigabytes, nothing is ever downloaded for no reason.

**Comment by j123b567** [comment]
https://github.com/j123b567/java-intelhex-parser/releases/tag/v1.0
